<?php

declare(strict_types=1);

$page_id = get_queried_object_id();
$field = static function ( string $name, mixed $fallback ) use ( $page_id ): mixed {
	$value = function_exists( 'get_field' ) ? get_field( $name, $page_id ) : null;
	return empty( $value ) ? $fallback : $value;
};
$image = static function ( mixed $value, string $fallback ): string {
	$url = is_numeric( $value ) ? wp_get_attachment_image_url( (int) $value, 'full' ) ?: wp_get_attachment_url( (int) $value ) : '';
	return $url ? esc_url( $url ) : $fallback;
};
$apply_url = esc_url( (string) $field( 'vacancies_application_url', 'https://forms.gle/ikGeworjH6wnAdSt6' ) );
$about_gallery = $field( 'vacancies_about_gallery', array( 'img/vacancies/about-1.jpg', 'img/vacancies/about-2.jpg', 'img/vacancies/about-3.jpg' ) );
$team_gallery = $field( 'vacancies_team_gallery', array_map( static fn( int $number ): string => sprintf( 'img/vacancies/team-%02d.jpg', $number ), range( 1, 13 ) ) );
$benefits = $field( 'vacancies_benefits', array(
	array( 'title' => 'Щорічні корпоративи', 'text' => 'Кофі-брейки, спільні поїздки в Карпати, квесткімнати та ігроклуби.', 'icon' => 'img/vacancies/benefit-events-3d.webp' ),
	array( 'title' => 'Постійна підтримка', 'text' => 'Регулярне навчання та щотижневі дзвінки, де команда вирішує робочі питання разом.', 'icon' => 'img/vacancies/benefit-support-3d.webp' ),
	array( 'title' => 'Достойна зарплата', 'text' => 'Зрозуміла система бонусів і навантаження, з якою ви впливаєте на свій дохід.', 'icon' => 'img/vacancies/benefit-pay-3d.webp' ),
) );
$vacancies = $field( 'vacancies_items', array(
	array( 'title' => 'Викладач програмування', 'image' => 'img/vacancies/programming-teacher.jpeg', 'summary' => 'Для енергійних викладачів, які впевнено працюють з комп’ютером і хочуть надихати дітей.', 'details' => '<h3>Хто нам потрібен?</h3><p>Енергійні та вмотивовані викладачі з активним підходом до роботи. Перевагою буде педагогічна або психологічна освіта.</p><h3>Обов’язки</h3><p>Проводити заняття за готовими методичними матеріалами, підтримувати дружню атмосферу, стежити за результатами учнів і вести звітність.</p><h3>Ми пропонуємо</h3><p>Роботу у будні та вихідні, стабільне підвищення оплати залежно від навантаження, навчання за рахунок компанії та сучасні кабінети.</p>' ),
	array( 'title' => 'Викладач англійської мови', 'image' => 'img/vacancies/english-teacher.jpg', 'summary' => 'Для викладачів, які допомагають дітям говорити англійською впевнено та із задоволенням.', 'details' => '<h3>Основні обов’язки</h3><p>Проводити групові заняття двічі на тиждень, перевіряти домашні завдання, мотивувати учнів і працювати у команді з методистом та менеджером.</p><h3>Для нас важливо</h3><p>Педагогічна або філологічна освіта, досвід роботи з дітьми, англійська від B2–C1 і впевнене володіння сучасними технічними засобами.</p><h3>Ми пропонуємо</h3><p>Підтримку команди, сучасні методичні матеріали й можливість професійного розвитку.</p>' ),
	array( 'title' => 'Клієнтський менеджер', 'image' => 'img/vacancies/client-manager.jpg', 'summary' => 'Для уважних менеджерів, яким подобається допомагати батькам обрати навчання для дитини.', 'details' => '<h3>Ваші обов’язки</h3><p>Презентувати школу батькам, організовувати навчальний процес, взаємодіяти з учнями, батьками та викладачами, вести базову фінансову звітність і працювати зі зворотним зв’язком.</p><h3>Сильні сторони</h3><p>Бажання вчитися, досвід продажів, стресостійкість, хороша дикція, вільна українська та самостійність у рішеннях.</p><h3>Ми пропонуємо</h3><p>Стабільну роботу, підтримку команди та прозорі можливості зростання.</p>' ),
) );
?>
<main class="vacancies-page">
	<section class="vacancies-hero" id="top"><div class="container vacancies-hero__inner"><div><h1><?php echo esc_html( (string) $field( 'vacancies_hero_title', 'Долучайтесь до нашої команди освітян!' ) ); ?></h1><p><?php echo esc_html( (string) $field( 'vacancies_hero_text', 'Запрошуємо натхненних викладачів і менеджерів, які готові ростити покоління нових ІТ-спеціалістів.' ) ); ?></p><a class="btn btn--yellow" href="<?php echo $apply_url; ?>" target="_blank" rel="noopener">Подати заявку</a></div><div class="vacancies-hero__media"><img src="<?php echo $image( $field( 'vacancies_hero_image', 0 ), 'img/vacancies/team-10.jpg' ); ?>" alt="Команда Logika"><img class="vacancies-hero__character" src="img/logika-character.svg" alt="" aria-hidden="true"></div></div></section>
	<section class="vacancies-about" id="about"><div class="container"><div class="vacancies-heading"><p class="vacancies-eyebrow">Про нас</p><h2><?php echo esc_html( (string) $field( 'vacancies_about_title', 'Навчаємо цікаво, легко та ефективно' ) ); ?></h2><div><?php echo wp_kses_post( (string) $field( 'vacancies_about_text', '<p>Logika — успішний освітній проєкт з 2018 року і понад 50 000 випускників. Ми навчаємо дітей 7–17 років програмуванню та англійської онлайн і офлайн.</p><p>Проводимо квести, їздимо в IT-табори та створюємо навчання, до якого хочеться повертатися.</p>' ) ); ?></div></div><div class="vacancies-photo-grid vacancies-photos"><?php foreach ( $about_gallery as $index => $photo ) : ?><img src="<?php echo $image( $photo, sprintf( 'img/vacancies/about-%d.jpg', $index + 1 ) ); ?>" alt="Команда Logika"><?php endforeach; ?></div></div></section>
	<section class="vacancies-benefits" id="benefits"><div class="container"><div class="vacancies-heading"><p class="vacancies-eyebrow">Наша атмосфера</p><h2><?php echo esc_html( (string) $field( 'vacancies_benefits_title', 'Робота роботою, а відпочинок за графіком :)' ) ); ?></h2><p><?php echo esc_html( (string) $field( 'vacancies_benefits_text', 'Працівники нашої компанії — наша команда і сім’я. Ми робимо атмосферу сприятливою для ефективної та приємної роботи.' ) ); ?></p></div><div class="vacancies-benefits__list"><?php foreach ( $benefits as $benefit ) : ?><article><img src="<?php echo $image( $benefit['icon'] ?? 0, 'img/vacancies/benefit-events.svg' ); ?>" alt=""><h3><?php echo esc_html( (string) ( $benefit['title'] ?? '' ) ); ?></h3><p><?php echo esc_html( (string) ( $benefit['text'] ?? '' ) ); ?></p></article><?php endforeach; ?></div></div></section>
	<section class="vacancies-gallery" aria-labelledby="team-gallery"><div class="container"><div class="vacancies-heading"><p class="vacancies-eyebrow">Разом поза роботою</p><h2 id="team-gallery"><?php echo esc_html( (string) $field( 'vacancies_team_gallery_title', 'Наші корпоративні теплі зустрічі' ) ); ?></h2></div><div class="vacancies-team-gallery"><?php foreach ( $team_gallery as $index => $photo ) : $url = $image( $photo, sprintf( 'img/vacancies/team-%02d.jpg', $index + 1 ) ); ?><button class="vacancies-team-gallery__item" type="button" data-vacancies-gallery-src="<?php echo esc_url( $url ); ?>" aria-label="<?php echo esc_attr( sprintf( 'Відкрити фото команди %d', $index + 1 ) ); ?>"><img src="<?php echo esc_url( $url ); ?>" alt="Зустріч команди Logika"></button><?php endforeach; ?></div></div></section>
	<dialog class="vacancies-lightbox" data-vacancies-lightbox aria-label="Перегляд фото команди"><button class="vacancies-lightbox__close" type="button" data-vacancies-lightbox-close aria-label="Закрити перегляд">×</button><img src="" alt="" data-vacancies-lightbox-image></dialog>
	<section class="vacancies-list" id="vacancies"><div class="container"><div class="vacancies-heading"><p class="vacancies-eyebrow">Приєднуйтесь</p><h2><?php echo esc_html( (string) $field( 'vacancies_list_title', 'Наші вакансії' ) ); ?></h2><p>Шукаємо викладачів та менеджерів для освітніх центрів по всій Україні.</p></div><div class="vacancies-list__grid"><?php foreach ( $vacancies as $index => $vacancy ) : $title = (string) ( $vacancy['title'] ?? '' ); ?><article class="vacancies-card"><img src="<?php echo $image( $vacancy['image'] ?? 0, 'img/vacancies/programming-teacher.jpeg' ); ?>" alt=""><div><h3><?php echo esc_html( $title ); ?></h3><p><?php echo esc_html( (string) ( $vacancy['summary'] ?? '' ) ); ?></p><button class="vacancies-details-trigger" type="button" data-vacancies-details-open="<?php echo (int) $index; ?>" data-vacancies-details-title="<?php echo esc_attr( $title ); ?>" aria-label="<?php echo esc_attr( 'Детальніше про ' . $title ); ?>">Детальніше</button><template data-vacancies-details-template="<?php echo (int) $index; ?>"><?php echo wp_kses_post( (string) ( $vacancy['details'] ?? '' ) ); ?></template></div></article><?php endforeach; ?></div></div></section>
	<dialog class="vacancies-details-dialog" data-vacancies-details-dialog aria-labelledby="vacancies-details-title"><button class="vacancies-details-dialog__close" type="button" data-vacancies-details-close aria-label="Закрити вакансію">×</button><h2 id="vacancies-details-title" data-vacancies-details-title></h2><div class="vacancies-details-dialog__content" data-vacancies-details-content></div><a class="btn btn--bordered" href="<?php echo $apply_url; ?>" target="_blank" rel="noopener">Подати заявку</a></dialog>
	<section class="vacancies-cta"><div class="container vacancies-cta__inner"><div><p class="vacancies-eyebrow">Твій наступний крок</p><h2><?php echo esc_html( (string) $field( 'vacancies_cta_title', 'Ми чекаємо на тебе!' ) ); ?></h2><p><?php echo esc_html( (string) $field( 'vacancies_cta_text', 'Наші школи розташовані по всій Україні, а також діє великий онлайн-відділ.' ) ); ?></p><a class="btn btn--yellow" href="<?php echo $apply_url; ?>" target="_blank" rel="noopener">Подати заявку</a></div><img src="<?php echo $image( $field( 'vacancies_cta_image', 0 ), 'img/vacancies/cta-character.svg' ); ?>" alt=""></div></section>
</main>
